# Generated by Django 3.1 on 2020-12-27 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BucketDetails',
            fields=[
                ('bucket_id', models.AutoField(primary_key=True, serialize=False)),
                ('bucket_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Bucket_table',
            },
        ),
        migrations.CreateModel(
            name='StatusDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Status_table',
            },
        ),
        migrations.CreateModel(
            name='TodoDetails',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('todo_name', models.CharField(max_length=50)),
                ('todo_status', models.CharField(max_length=10)),
                ('todo_bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApi.bucketdetails', to_field='bucket_name')),
            ],
            options={
                'db_table': 'Todo_table',
            },
        ),
    ]
