# Generated by Django 3.1 on 2020-12-27 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusdetails',
            name='status_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tododetails',
            name='todo_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApi.statusdetails', to_field='status_name'),
        ),
    ]
